eRecipesSite/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/', views.RecipeListView.as_view(), name='recipes'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(), name='recipe-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),

    # path('recipe/<int:pk>/update/', views.update_last_made, name='update-last-made'), # i'd sure like the recipe field to be better bring this back later?
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
# urlpatterns += [
#     path('static/media/recipes/<str:pk>', )
# ]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('recipe/create/', views.RecipeCreate.as_view(), name='recipe-create'),
    path('recipe/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipe-update'),
    path('recipe/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipe-delete'),
]

urlpatterns += [
    path('search', views.RecipeSearch, name='search'),
]

eRecipesSite/eRecipesSite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eRecipesSite/catalog/models.py
from django.db import models

# Create your models here.
class Cuisine(models.Model):
    """Model representing a recipe cuisine."""
    name = models.CharField(max_length=200, help_text='Enter a recipe cuisine (e.g. Italian, Japanese)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

# Create your models here.
class Diet(models.Model):
    """Model representing a diet that a recipe may fall under."""
    name = models.CharField(max_length=200, help_text='Enter a diet (e.g. Vegan, Gluten-free)')

    # probably should include diets this includes as a super-set

    def __str__(self):
        """String for representing the Model object."""
        return self.name


from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from datetime import date
import uuid # Required for unique book instances
from django.db.models.functions import Upper
import django # could improve this
import random
class Recipe(models.Model):
    """Model representing a recipe."""
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular recipe across whole library')

    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True) # default is for testing only

    # need to figure out ingredients and stuff...
    # later fields: ingredients (quantities? uniqueness?) last made, rating, personal notes, pictures??? 
    # uploaded, whatever else

    description = models.TextField(max_length=1000, help_text='Enter a brief description of the recipe', blank=True, null=True)
    # isbn = models.CharField('ISBN', max_length=13, unique=True,
    #                          help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    cuisine = models.ManyToManyField(Cuisine, help_text='Select a cuisine for this recipe', default=None, blank=True)
    diet = models.ManyToManyField(Diet, help_text='Select a diet for this recipe', default=None, blank=True)

    last_made = models.DateField(default=django.utils.timezone.now)

    recipe_photo = models.ImageField(upload_to='catalog/static/media/recipes/images', blank=True, null=True, help_text="Upload an image of the recipe here")
    recipe_pdf = models.FileField(upload_to='catalog/static/media/recipes/pdfs', blank=True, null=True, help_text="Or, if you prefer, upload a pdf here.")

    words = models.TextField(default = None, null=True, blank=True)

    class Meta:
        ordering = [Upper('title')]

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this recipe."""
        return reverse('recipe-detail', args=[str(self.id)])

# probably could have some other things in here
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    biography = models.TextField(max_length=1000, help_text='Enter a brief biography', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name}'

eRecipesSite/catalog/forms.py
import datetime
from datetime import date

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class UpdateLastMadeForm(forms.Form):
    years = list(range(2010,2024))
    last_made = forms.DateField(help_text="Enter the date the recipe was last made.",widget=forms.SelectDateWidget(years = years))

    def clean_last_made(self):
        data = self.cleaned_data['last_made']

        # Check if a date is not in the past.
        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - date in the future'))

        # Check if a date is in the allowed range (+4 weeks from today).
        # if data > datetime.date.today() + datetime.timedelta(weeks=4):
        #     raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data



# from django.forms import ModelForm

# from catalog.models import Recipe

# class UpdateLastMadeForm(ModelForm):
#     def clean_last_made(self):
#        data = self.cleaned_data['last_made']

#        # Check if a date is not in the past.
#        if data > datetime.date.today():
#            raise ValidationError(_('Invalid date - date in the future'))

#     #    # Check if a date is in the allowed range (+4 weeks from today).
#     #    if data > datetime.date.today() + datetime.timedelta(weeks=4):
#     #        raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

#        # Remember to always return the cleaned data.
#        return data

#     class Meta:
#         model = Recipe
#         fields = ['last_made']
#         labels = {'last_made': _('Last made')}
#         help_texts = {'last_made': _('Enter when the recipe was last made.')}

eRecipesSite/catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Recipe, Author, Cuisine, Diet

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_recipes = Recipe.objects.all().count()

    # Available books (status = 'a')
    # num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_diets = Diet.objects.count()

    num_cuisines = Cuisine.objects.count()

    context = {
        'num_recipes': num_recipes,
        # 'num_instances': num_instances,
        # 'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_cuisines': num_cuisines,
        'num_diets': num_diets,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

class RecipeListView(generic.ListView):
    model = Recipe
    paginate_by = 10

class RecipeDetailView(generic.DetailView):
    model = Recipe

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author



import datetime

# from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import UpdateLastMadeForm

# @login_required
# @permission_required('catalog.can_mark_returned', raise_exception=True)
def update_last_made(request, pk):
    """View function for updating the last time a recipe was used."""
    print(request, pk)
    recipe = get_object_or_404(Recipe, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = UpdateLastMadeForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            recipe.last_made = form.cleaned_data['last_made']
            recipe.save()

            # redirect to a new URL:
            uri = request.build_absolute_uri()
            return HttpResponseRedirect(uri[:uri.strip('/').rfind('/')]) # this is kind of janky

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_last_made = datetime.date.today()
        form = UpdateLastMadeForm(initial={'last_made': proposed_last_made})

    context = {
        'form': form,
        'recipe': recipe,
    }

    return render(request, 'catalog/update_last_made.html', context)

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'biography']
    # initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'biography']
    fields = '__all__' # Not recommended (potential security issue if more fields added)

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


from catalog.models import Recipe

"""
https://stackoverflow.com/questions/62727762/django-call-custom-function-within-generic-views
class QuoteUpdate(UpdateView):
    model = Quote
    fields = ['quote_text']
    
    def my_custom_function(self):  
        # your code
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.my_custom_function()
        return super().post(request, *args, **kwargs)
        """
import pdf2image
import cv2

# extracts specified ingredient from recipe dict as a new singleton 
# dictionary
def process_word(ingredient):
    
    ingredient = ingredient.lower().strip()

    punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    word = ingredient
    for c in word.lower().strip():
        if c in punctuation:
            word = word.replace(c, "")
    return word

# create a new dictionary that extracts ingredients from the recipe_dict
def process_ingredients(ing_lst):
    d = {}

    for ingredient in ing_lst:
        processed = process_word(ingredient)
        d[processed] = d.get(processed, 0) + 1 # dict.update(process_word(ingredient, recipe_dict))
    return d

from pathlib import Path
from django.core.files import File
import pytesseract
def form_valid_helper(self, form):
    # isvalid = super(RecipeCreate, self).form_valid(form)
    # s = Subcategory.objects.get(pk=self.kwargs['subcat_id'].encode('utf-8'))
    # this_object = self.get_object()
    # print("hello world")
    # print(self.request.POST.keys())
    # self.object.save()
    # print(self.request.FILES)

    if self.request.FILES.get('recipe_pdf'):
        # print("Now attempting to process a pdf, hahaha")
        pdf_path = str(self.object.recipe_pdf)
        # print()
        pdf = pdf2image.convert_from_path(pdf_path)

        png_path_tail = os.path.splitext(os.path.split(pdf_path)[1])[0]+".png"
        png_path_head = os.path.split(os.path.split(pdf_path)[0])[0] # i'm sure there is a better way to do this
        
        images = []
        for i in range(len(pdf)):
            png_path = f'{png_path_head}/images/{i+1}-{png_path_tail}'
            # print("png path", png_path)
            pdf[i].save(png_path, 'PNG')
            if i == 0:
                # self.object.recipe_picture = f'{png_path}'
                # self.object.save()
                path = Path(png_path)
                with path.open(mode='rb') as f:
                    self.object.recipe_photo = File(f)
                    self.object.save()# update_fields=['recipe_photo'])
                    # print("saved")
            images.append(cv2.imread(png_path))
            

            words = []
            for img in images:
                text = pytesseract.image_to_string(img)
                words += text.split()
            ingredient_dictionary = process_ingredients(words)

            self.object.words = ingredient_dictionary
            self.object.save()
            # print(process_ingredients(words))
        # print(pdf_path)
        

        # need path to jpg land

        # pdf[0].save(f'{self.object.recipe_title}_cbbr_page{1}.png', 'PNG')
        # self.object.recipe_picture = 


    # if self.request.FILES.get('recipe_photo'):
    #     print("hello world 2")
    #     image = form.cleaned_data['recipe_photo']
    #     # print("hello world 2")
    #     print("keys")
    #     for key in form.cleaned_data:
    #         print(key, form.cleaned_data[key])
    #     # title = form.cleaned_data['art_title'].encode('utf-8')
    #     # year_of_creation = form.cleaned_data['year_of_creation']
    #     m = Recipe.objects.get_or_create(recipe_photo=image)[0]
        # Recipe.objects.recipe_photo.add(m) # idk
        # self.object.save()

import os
# from django import Media
# this needs to be replaced with something more boutique
class RecipeCreate(CreateView):
    model = Recipe
    fields = ['title', 'author', 'description', 'cuisine', 'diet', 'last_made', 'recipe_photo', 'recipe_pdf']

    def form_valid(self, form):
        isvalid = super(RecipeCreate, self).form_valid(form)
        form_valid_helper(self, form)
        return isvalid

    # def post(self, request, *args, **kwargs):
    #     # self.object = self.get_object() // what does this do
    #     self.process_files()
    #     return super().post(request, *args, **kwargs)
    # # initial = {'date_of_death': '11/06/2020'}

class RecipeUpdate(UpdateView):
    model = Recipe
    fields = ['title', 'author', 'description', 'cuisine', 'diet', 'last_made', 'recipe_photo', 'recipe_pdf'] # Not recommended (potential security issue if more fields added)

    def form_valid(self, form):
        isvalid = super(RecipeUpdate, self).form_valid(form)
        form_valid_helper(self, form)
        return isvalid

class RecipeDelete(DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipes')



#models.py
from .models import *
#views

def RecipeSearch(request):
    """ search function  """
    if request.method == "POST":
        query_name = request.POST.get('ingredients', None)
        if query_name:
            words_results = Recipe.objects.filter(words__contains=query_name) # need to adjust this to properly filter
            title_results = Recipe.objects.filter(title__contains=query_name)
            context={"title_results":title_results, "words_results":words_results, "query_name":query_name}
            return render(request, 'recipe-search.html', context=context)
    print('didn"t find anything')
    return render(request, 'recipe-search.html')
    # return render(request, 'index.html', context=context)

# User.objects.filter(data__campaigns__contains=[{'key': 'value'}])
"""
context = {
        'num_recipes': num_recipes,
        # 'num_instances': num_instances,
        # 'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_cuisines': num_cuisines,
        'num_diets': num_diets,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)
    """

eRecipesSite/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

eRecipesSite/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{author.last_name}}</h1>

  <br>
  <p><strong>Biography:</strong> {{ author.biography }}</p> 
  

  {% comment %} <p><strong>Author:</strong> <a href="">{{ recipe.author }}</a></p> <!-- author detail link not yet defined --> {% endcomment %}
  {% comment %} <p><strong>Summary:</strong> {{ recipe.summary }}</p>  {% endcomment %}
  {% comment %} <p><strong>ISBN:</strong> {{ book.isbn }}</p> {% endcomment %}
  {% comment %} <p><strong>Cuisine:</strong> {{ recipe.cuisine.all|join:", " }}</p> {% endcomment %}
  {% comment %} <p><strong>Diet:</strong> {{ recipe.cuisine.all|join:", " }}</p> {% endcomment %}

  <div style="margin-left:20px;margin-top:20px">
    {% comment %} <h4>Copies</h4> {% endcomment %}

    {% for recipe in author.recipe_set.all %}
      <hr>
      {% comment %} <p> {{ recipe.title }} </p> {% endcomment %}
      <a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a> 
      {% comment %} <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p> {% endcomment %}
      {% comment %} {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p> {% endcomment %}
    {% endfor %}
  </div>
  <br><br>
  <a href="{{ author.get_absolute_url }}/update">Edit</a></p> <!-- author detail link not yet defined -->
  <a href="{{ author.get_absolute_url }}/delete">Delete</a></p> <!-- author detail link not yet defined -->
{% endblock %}

eRecipesSite/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

eRecipesSite/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a> 
        {% comment %} could add something about publication etc {% endcomment %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}
{% endblock %}

eRecipesSite/catalog/templates/catalog/recipe_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Recipe</h1>

<p>Are you sure you want to delete the recipe: {{ recipe.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

eRecipesSite/catalog/templates/catalog/recipe_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ recipe.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ recipe.author.get_absolute_url }}">{{ recipe.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ recipe.summary }}</p> 
  {% comment %} <p><strong>ISBN:</strong> {{ book.isbn }}</p> {% endcomment %}
  <p><strong>Cuisine:</strong> {{ recipe.cuisine.all|join:", " }}</p>
  <p><strong>Diet:</strong> {{ recipe.diet.all|join:", " }}</p>
  <p><strong>Last made:</strong> {{ recipe.last_made }}</p> 
  {% if recipe.recipe_photo %}
    <img src = "../../{{ recipe.recipe_photo }}" alt = "A photo of the recipe." width="600" height=f"{600*11/8.5}">
  {% endif %}
  <br><br>
  <a href="{{ recipe.get_absolute_url }}/update">Edit</a></p> <!-- author detail link not yet defined -->
  <a href="{{ recipe.get_absolute_url }}/delete">Delete</a></p> <!-- author detail link not yet defined -->

  <div style="margin-left:20px;margin-top:20px">
  </div>
{% endblock %}

eRecipesSite/catalog/templates/catalog/recipe_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

eRecipesSite/catalog/templates/catalog/recipe_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Recipe List</h1>
  {% if recipe_list %}
  <ul>
    {% for recipe in recipe_list %}
      <li>
        <a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a> ({{recipe.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no recipes in the library.</p>
  {% endif %}
{% endblock %}

eRecipesSite/catalog/templates/catalog/update_last_made.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Update the date for: {{ recipe.title }}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}